fix: `DataladBranchConfig` now treated as read-only in a bare repository
This fixes

```
RuntimeError: Source DataladBranchConfig[blob:HEAD:.datalad/config] is (presently) not writable
```

which was caused by `DataladBranchConfig` assuming a writable
configuration source, when in fact it isn't (always). The
correct runtime tests are already made otherwise, so this change
only switches to a lower-level helper method that does not
trigger the inappropriate test.